/**
 * Loads the session's schedules from the server.
 *
 * The schedules live in the Python process (generated by the Schedule Generator or
 * imported with Load JSON). We fetch them through the export route, which returns the
 * library's JSONWriter format (README → "Schedule JSON format"), so scheduleData.js
 * can read them the same way it reads a file.
 *
 * `refreshKey` changes whenever the polled app state says the schedules or the
 * generation status changed, which triggers a new fetch.
 */
import { useEffect, useState } from "react";

import { api } from "../../api/client.js";
import { getScheduleList } from "./scheduleData.js";

/** Errors that just mean "there are no schedules yet". */
function isEmptyError(error) {
  return error?.status === 404 || error?.status === 409;
}

/** Load schedules on refresh-key changes or reload calls, returning items, loading, and error state. */
export function useSchedules(refreshKey) {
  const [result, setResult] = useState({ loading: true, items: [], error: null });
  const [reloadCount, setReloadCount] = useState(0);

  useEffect(() => {
    let cancelled = false;

    api.schedules
      .exportFile({ which: "all", format: "json" })
      .then(({ content }) => {
        if (cancelled) return;
        let data;
        try {
          data = JSON.parse(content);
        } catch {
          setResult({
            loading: false,
            items: [],
            error: "Unable to load schedules: the server returned invalid JSON.",
          });
          return;
        }
        setResult({ loading: false, items: getScheduleList(data), error: null });
      })
      .catch((error) => {
        if (cancelled) return;
        setResult({
          loading: false,
          items: [],
          error: isEmptyError(error) ? null : error.message,
        });
      });

    return () => {
      cancelled = true;
    };
  }, [refreshKey, reloadCount]);

  return { ...result, reload: () => setReloadCount((count) => count + 1) };
}
