/**
 * Loads one schedule from the server, already grouped by room and lab or by faculty.
 *
 * The schedules live in the Python process (generated by the Schedule Generator or
 * imported with Load JSON). The grouping is done by the Model (`ScheduleSet.view` in
 * src/zimpasta/model/schedules.py, covered by pytest), so the View only displays it.
 * See docs/web-api.md → `GET /api/schedules/{number}?group=room|faculty`.
 *
 * `refreshKey` changes whenever the polled app state says the schedules or the
 * generation status changed, which triggers a new fetch.
 */
import { useEffect, useState } from "react";

import { api } from "../../api/client.js";

/** The server's way of saying "there are no schedules yet"; every other error is real. */
function isEmptyError(error) {
  return error?.code === "no_schedules";
}

/**
 * Load schedule `number` (counting from 1) grouped by `group` ("room" or "faculty").
 * `view` is the server's reply, or null when there are no schedules.
 */
export function useSchedules({ number, group, refreshKey }) {
  const [result, setResult] = useState({ loading: true, view: null, error: null });
  const [reloadCount, setReloadCount] = useState(0);

  useEffect(() => {
    let cancelled = false;

    api.schedules
      .view(number, group)
      .then((view) => {
        if (!cancelled) setResult({ loading: false, view, error: null });
      })
      .catch((error) => {
        if (cancelled) return;
        setResult({ loading: false, view: null, error: isEmptyError(error) ? null : error.message });
      });

    return () => {
      cancelled = true;
    };
  }, [number, group, refreshKey, reloadCount]);

  return { ...result, reload: () => setReloadCount((count) => count + 1) };
}
